### ISSUE TITLE
Bitepoint value now showing only 100 or 0

### ISSUE THREAD

**Issue by Thingamejig** [andreasdahl1987/DahlDesignDDC#1]
so I am having a strange problem. Sometimes the bitepoint raw data from iRacing (running the Renault 3.5) only gives 100 or 0 with no in between. 
I’m running a Nextion screen in a hand built Renault 3.5 formula steering wheel with custom graphics to emulate the iRacing Renault 3.5. Everything is fine except the bitepoint value. 

![4BD144C6-5BB8-43B3-B1F8-46EE5E99C870](https://user-images.githubusercontent.com/120469755/207319943-dc4c3800-5ebd-44a0-bd4c-0a711af3f808.png)
![FAF7A82F-D35A-42BD-8AD3-2DBCE506A519](https://user-images.githubusercontent.com/120469755/207319980-d934a58f-d244-42c1-b806-520e0f65cf81.png)
![62C2CF6F-B7F7-4150-B7B0-033116FC5363](https://user-images.githubusercontent.com/120469755/207319986-d891bc8f-cc3c-4517-bb25-7a9d3a092cef.jpeg)
![F429F022-2207-4BDF-B385-3BC30584E061](https://user-images.githubusercontent.com/120469755/207320006-5b8408c4-7c74-43b5-936a-9ca7304076c1.png)

![0B149029-B85D-48AD-AFFB-215DFACDDCC6](https://user-images.githubusercontent.com/120469755/207322578-6422c1f1-46db-4c39-943a-daab1bb12728.jpeg)

I have replaced the up/down push button encoder thinking it was faulty but the new one does the same and the old one has been also confirmed ok. 

It was working ok for hours with all 4 bitepont adjustment modes working fine but all of a sudden now I only get 100 or 0 for the bite point data? Is this a bug? I can see the real-time RAW  data value coming from iRacing into SimHub  being reported though the Nextion mapping editor and it only toggles between these two values with no in between. I can confirm the master and slave clutches work because I have created a text field in my Nextion screen to see the real-time clutch data and the clutches calibrate fine in iRacing and also calibrate fine in windows gamepad/joystick calibration utility. The slave clutch also is affected by the bite value so doing what it should. Problem is without bitepoint adjustment, the clutches can’t be used as intended.

**Comment by andreasdahl1987** [comment]
This is a bit strange, particulary the part where it has been working for hours and then suddenly stops working. I think we'll get to the bottom of this. First of all, the clutch bite point comes from steering wheel -> SimHub -> DahlDesign plugin -> SimHub. So iRacing doesn't have anything to do with this. 

1. The fact that the slave clutch still works means the displayed bitePoint from the [DahlDesign.DDCbitePoint] property is not the actual bite point. When does it move between 0 and 1? When you try to adjust bite point?
2. How are you getting a value for both slave and master clutch? The DDC dual clutch function only produces a single clutch value.
3. Can you zip your project code an upload to this rapport please? :)
4. f you take a look in the windows USB game controller window: 
![image](https://user-images.githubusercontent.com/40788634/207327831-92e4f3f3-e32a-4495-9410-836de72a0df3.png)
The bite point should be visible as one of the joystick axis. Can you see it moving when trying to adjust the bite point? This is the raw data comming from the wheel. 
5. Which version of the plugin are you using?
6. Is the issue resolved if you disconnect/reconnect the wheel's USB?
