### ISSUE TITLE
Missing setup() and loop() on raspberry pi pico when not using LEDs

### ISSUE THREAD

**Issue by cazeaux** [andreasdahl1987/DahlDesignDDC#18]
Hello

When we use the library without LEDs (all `LED<x>COUNT` are 0), the `setup()` and `main()` functions are not set, leading to compilation error.

This is due to 
```c
#if (LED1COUNT + LED2COUNT + LED3COUNT + LED4COUNT > 0 && BOARDTYPE == 2)
```

The fix is easy, proposed in a PR associated

**Comment by andreasdahl1987** [comment]
Aaah man, flipping what is done on which core was the last thing we did - which made the LED control from SimHub work perfectly stable. Didn't think about this, thanks for finding out and adding the PR so soon :D
