### ISSUE TITLE
LED or Power Control using PWM and Mosfet.

### ISSUE THREAD

**Issue by ZebbeBa** [andreasdahl1987/DahlDesignDDC#22]
The Bluepill and Freejoy have a sweet feature that allows users to turn a power circuit on and off using a PWM and a dedicated mosfet or transistor.

This can be used to power backlighting circuits or RGB leds- 
One button is assigned to turn the PWM signal high or low and allowing users to turn the backlighting on and off.

The benefit is that you can use "normal" led instead of WS2812B and are not depended on any clinet software.  
And the circuitry is very simple. 

Freejoy Wiki article on the topic: 
https://github.com/FreeJoy-Team/FreeJoyWiki/blob/master/eng/RGB-LED-configuration.md

![image](https://user-images.githubusercontent.com/77197833/227798849-ba27f952-da4a-47f8-83df-cb516ddc7df7.png)

**Comment by andreasdahl1987** [comment]
Great suggestion, I'll do some experiments and eventually send you something for testing :) As you said, this is very light on hardware/software, and could be extremely useful - so no good reason to not include it.

**Comment by andreasdahl1987** [comment]
Added in 2.9
